// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "NetworkSoundRelay.generated.h"

class USoundBase;
class APlayerState;

/**
 * Minimal replicated actor whose sole purpose is to relay sounds via NetMulticast.
 * Automatically spawned by UNetworkSoundSubsystem — do not place it manually in the world.
 *
 * Play flow:
 *   Instigating client → Server_BroadcastSound (Server RPC, carries Handle)
 *     → Multicast_PlaySound → all clients except the instigator spawn and register
 *                             the AudioComponent at reduced volume under the given Handle.
 *
 * Stop flow:
 *   Any client → Server_BroadcastStop (Server RPC, carries Handle)
 *     → Multicast_StopSound → all clients look up the Handle and stop the AudioComponent.
 */
UCLASS(NotBlueprintable)
class COREGAMEPLAY_API ANetworkSoundRelay : public AActor
{
	GENERATED_BODY()

public:

	ANetworkSoundRelay();

	/**
	 * Volume multiplier applied on clients that are not the instigator.
	 * Range: 0.0 to 1.0.
	 */
	UPROPERTY(EditDefaultsOnly, Category = "Sound", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float RemoteVolumeMultiplier = 0.4f;

	/**
	 * Sends a sound request to the server so it can be relayed via Multicast.
	 * Should be called from a client (or the server itself).
	 *
	 * @param Sound           The sound asset to play.
	 * @param Location        World position at which to play the sound.
	 * @param InstigatorState PlayerState of the instigator, used to skip playback on their machine.
	 * @param Handle          Unique handle generated by UNetworkSoundSubsystem, used to stop the sound later.
	 */
	UFUNCTION(Server, Reliable)
	void Server_BroadcastSound(USoundBase* Sound, FVector Location, APlayerState* InstigatorState, int32 Handle);

	/**
	 * Sends a stop request to the server so it can be relayed via Multicast.
	 * Should be called from a client (or the server itself).
	 *
	 * @param Handle The handle of the sound to stop, as returned by PlayNetworkedSound().
	 */
	UFUNCTION(Server, Reliable)
	void Server_BroadcastStop(int32 Handle);

private:

	UFUNCTION(NetMulticast, Unreliable)
	void Multicast_PlaySound(USoundBase* Sound, FVector Location, APlayerState* InstigatorState, int32 Handle);

	// Reliable: a missed stop packet would leave a looping sound running indefinitely.
	UFUNCTION(NetMulticast, Reliable)
	void Multicast_StopSound(int32 Handle);
};
