// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "IngredientTypes.h"
#include "InteractionBase.h"
#include "Misc/DataValidation.h"
#include "ItemTransformation.generated.h"

class UItemAsset;
class UActivityAsset;

UCLASS()
class RECIPES_API UItemTransformation : public UPrimaryDataAsset
{
	GENERATED_BODY()
	
public:
	UFUNCTION(BlueprintPure, Category = "Step|Validation")
	bool HasInputConstraints() const;

	UFUNCTION(BlueprintCallable, Category = "Step|Validation")
	bool IsStepDefinitionValid(FText& OutFailureReason) const;

#if WITH_EDITOR
	virtual EDataValidationResult IsDataValid(FDataValidationContext& Context) const override;
#endif


	/** Display name for this linear recipe step. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Step")
	FText StepName;

	/** Required input item for this step (optional if only tag/state validation is used). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Input")
	TObjectPtr<UItemAsset> InputItem;

	/** Number of input items consumed by this step. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Input", meta = (ClampMin = "1"))
	int32 InputQuantity = 1;

	/** Required data tags that must be present on the input item. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Input")
	TArray<FName> RequiredItemDataTags;

	/** Required transformation flags that must be present on the input item. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Input")
	TArray<FName> RequiredTransformationFlags;

	/** If true, input must be an ingredient with Processed type. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Input")
	bool bRequireProcessedIngredient = false;

	/** Required ingredient state flags on the input ingredient. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Input")
	TArray<EIngredientStateFlag> RequiredIngredientStateFlags;

	/** Required ingredient state tags on the input ingredient. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Input")
	TArray<FName> RequiredIngredientStateTags;

	/** Recipe operator activity (e.g. Mix, Simmer, Cut). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Operator")
	TObjectPtr<UActivityAsset> Activity;

	/** Interaction definition executed by this operator (QTE/IFT). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Operator")
	TObjectPtr<UInteractionDefinitionAsset> InteractionDefinition;

	/** Optional processing duration override used when generating instructions. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Operator", meta = (ClampMin = "0.0"))
	float ProcessingDuration = 0.0f;

	/** If true, actor must remain in interaction distance while processing this step. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Operator")
	bool bRequiresProximity = true;

	/** Item generated after this step is resolved. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Output")
	TObjectPtr<UItemAsset> OutputItem;

	/** Number of output items generated by this step. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Output", meta = (ClampMin = "1"))
	int32 OutputQuantity = 1;

	/** Optional metadata tags describing the produced state. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Output")
	TArray<FName> OutputDataTags;

	/** Optional transformation flags describing the produced state. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Output")
	TArray<FName> OutputTransformationFlags;

	/** Base score gained when this step is completed. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Scoring")
	int32 BaseStepScore = 100;

	/** Multiplier applied to interaction score for this step. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Scoring", meta = (ClampMin = "0.0"))
	float InteractionScoreMultiplier = 1.0f;

	/** Additional penalty applied when this step interaction fails/timeouts. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Scoring", meta = (ClampMin = "0"))
	int32 FailurePenalty = 0;
};
